# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\"R\n\x0eUsuarioRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07usuario\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\"\n\x0fResponseUsuario\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x07usuario\x12\x31\n\x0c\x63rearUsuario\x12\x0f.UsuarioRequest\x1a\x10.ResponseUsuariob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USUARIOREQUEST']._serialized_start=17
  _globals['_USUARIOREQUEST']._serialized_end=99
  _globals['_RESPONSEUSUARIO']._serialized_start=101
  _globals['_RESPONSEUSUARIO']._serialized_end=135
  _globals['_USUARIO']._serialized_start=137
  _globals['_USUARIO']._serialized_end=197
# @@protoc_insertion_point(module_scope)
